### ISSUE TITLE
Problem with loading via webpack

### ISSUE THREAD

**Issue by mefjuu** [bezoerb/htmlsave#1]
Hi,
There is a problem with bundling htmlsave (installed via NPM) with [webpack](http://webpack.github.io/):

```
Critical dependencies:
3:439-446 This seem to be a pre-built javascript file. Even while this is possible, it's not recommended. Try to require to orginal source to
get better results.
```

PS. Thanks for very useful tool BTW! :)

**Comment by bezoerb** [comment]
I never used webpack. I'll try to find some free time to see how this can be fixed.

**Comment by bezoerb** [comment]
you could configure an alias in your webpack config

``` javascript
resolve: {
    alias: {
        'htmlsave': path.join(__dirname, 'node_modules/htmlsave/src/htmlsave')
    }
}
```
