### ISSUE TITLE
Truncates even when string length less than maxLength

### ISSUE THREAD

**Issue by lucaskuzma** [bezoerb/htmlsave#2]
output:
this text has 370 characters and we are truncating to 420 sensory claymore mine free-market camera Chiba jeans engine denim tube alcohol. weathered knife papier-mache artisanal corporation boy augmented reality footage otaku table modem digital city dome film boat camera car uplink beef noodles render-farm nodal point wonton soup man hotdog RAF skyscraper market human
370
this text has 370 characters and we are truncating to 420 sensory claymore mine free-market camera Chiba jeans engine denim tube alcohol. weathered knife papier-mache artisanal corporation boy augmented reality footage otaku table modem digital city dome film boat camera car uplink beef noodles render-farm nodal point wonton soup man hotdog RAF skyscraper market...

from input:
`<body> <script src='https://rawgit.com/bezoerb/htmlsave/master/dist/htmlsave.min.js'></script> <script> var str='this text has 370 characters and we are truncating to 420 sensory claymore mine free-market camera Chiba jeans engine denim tube alcohol. weathered knife papier-mache artisanal corporation boy augmented reality footage otaku table modem digital city dome film boat camera car uplink beef noodles render-farm nodal point wonton soup man hotdog RAF skyscraper market human'; document.write(str); document.write('<br/>'); document.write(str.length); document.write('<br/>'); document.write(htmlsave.truncate(str,420)); </script> </body>`

**Comment by bezoerb** [comment]
@lucaskuzma fixed this in v1.0.0
